### ISSUE TITLE
Code Page 1252

### ISSUE THREAD

**Issue by FrancisFaure** [mattslay/Visual-FoxPro-language-template-for-Visual-Studio-Code#1]
Hi Matt,
- Someone just wrote me that you worked on same project as me (or I worked on the same project as your) : add VFP Language in VS Code !
- My GitHub for this project (shown in VFP French speaking user group in march) is : https://github.com/FrancisFaure/vfp_tmlanguage_generator
  My actual problem is VSCode, by default use encoding UTF-8 and not Windows 1252
  You can see my request at VScode team  here : https://github.com/Microsoft/vscode/issues/4891
  Have you solved codepage problem ?
  Sorry for my bad english
  With best regards
  Francis

**Comment by mattslay** [comment]
Hello friend - I have not actually used VS Code to modify PRG diles, so I have not encountered any problems related to this codepage issue.

Now that you mention it, when I open a PRG in VS Code, I see that it shows UTF-8 encoding in the bottom of the app. The code looks fine when I see it in the editor. So, I do not understand what the issue is...  Will something bad happen if I save the PRG after it is opened in UTF-8 encoding?

Please explain how this could impact PRG files so I can understand more abou this.

**Comment by mattslay** [comment]
@FrancisFaure - I added a link to your project on the readme file in my project. I wanted to point people to yours also, because it may well be better than mine. You can see it on the front page of my github repo at the top of the readme.md

Good luck to you.

**Comment by FrancisFaure** [comment]
Hi Friend

> Please explain how this could impact PRG files so I can understand more abou this.
> I'll make print screen and send by email 
> Regards
> Francis

**Comment by FrancisFaure** [comment]
![for_matt](https://cloud.githubusercontent.com/assets/1745022/14257907/42ab19bc-faa0-11e5-9f3e-e381dfecd4e1.jpg)

Dear Matt,
Try this VFP Code :

`
CLEAR
TEXT TO m.test NOSHOW
  vfp=MESSAGEBOX("1x attaché-case : price 100 €") && Windows 1252 (VFP default file encoding)
  vscode=MESSAGEBOX("1x attachÃ©-case : price 100 â‚¬") && UTF-8 (VS Code default file encoding)

ENDTEXT

=STRTOFILE(m.test, "c:\temp\test.prg")

RUN /N "C:\Program Files (x86)\Microsoft VS Code\Code.exe" c:\temp\test.prg && edit TEST.PRG in VSCode
- modify test.prg in VS Code (with UTF-8 file encoding by default), save, and open in VFP... 
- vfp=MESSAGEBOX("1x attachï¿½-case : price 100 ï¿½") 

NOTE we need VS Code support other code page .PRG files ... because VFP don't support UTF-8...
`

Regards
Francis

Edit : print screen added
