### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by FrancisFaure** [mattslay/Visual-FoxPro-language-template-for-Visual-Studio-Code#2]
Hi Matt,

Yesterday, I added Visual FoxPro Snippets 
you can take a look at 
https://github.com/FrancisFaure/vfp_tmlanguage_generator/blob/master/Snippets.md
if you are interested, you can add my vfp.snippets.json in your project...

Currently, VSCode team don't have a solution for fix "encoding files by extension of filenames",
It's a big problem for us to use VSCode on PRG files....

the next step is to implement "IntelliSense" :
I think it's easy with VFP. 
But I have googled without success. 
I don't find simple samples.
Have you worked for implement VFP IntelliSense in VSCode? 
Have you found ressources for VSCode IntelliSense ?

sorry for my bad English and with my best regards
Francis

**Comment by mattslay** [comment]
_Have you worked for implement VFP IntelliSense in VSCode?_ 
_Have you found ressources for VSCode IntelliSense ?_

No and No.  Your work with the snippets looks nice great.

As far as Intellisense, are you aware of the VFPX project called **IntellisenseX** that adds some really powerful Intellisense capabilities to VFP?  Please check it out. It is well documented and has many videos to explain.  

[https://vfpx.codeplex.com/wikipage?title=Thor%20IntellisenseX](https://vfpx.codeplex.com/wikipage?title=Thor%20IntellisenseX)

**Comment by FrancisFaure** [comment]
Hi Matt,
FYI: a good news: VS Code (Insiders of this week) manage now "files.encoding" (CODE PAGE)
best regards
Francis
