### ISSUE TITLE
Add Folding/Collapsing feature to Procedures

### ISSUE THREAD

**Issue by eallende** [mattslay/Visual-FoxPro-language-template-for-Visual-Studio-Code#3]
Hi!
Is it too difficult to add Folding feature to Procedures? How can i do so?

**Comment by Mike-SP** [comment]
Code folding appears to be already there. You need to hover over the left side of the code structure to reveal a dropdown toggle.

**Comment by mattslay** [comment]
Yes, @Mike-SP is correct. It works perfectly!  I had never noticed this before.

![2016-12-07_9-10-18](https://cloud.githubusercontent.com/assets/309016/20973151/31e04362-bc5d-11e6-8f58-008004b081ea.png)

**Comment by Mike-SP** [comment]
IMO, code folding is the biggest feature that is missing from the native VFP editor. Too bad VSC doesn't work for VFP form code too :(

**Comment by mattslay** [comment]
This feature *is* supported. See home page readme for a screenshot.
