### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by JulioNobre** [mattslay/Visual-FoxPro-language-template-for-Visual-Studio-Code#6]
First of all, Mads, let me thank you on this great extension!

Just came here to point out that on page https://github.com/mattslay/Visual-FoxPro-language-template-for-Visual-Studio-Code,

where there is `%USERPROFILE%.vscode\extensions`

it should be `%USERPROFILE%\.vscode\extensions`

To fix, you just need to add a the first slash.

Ok, I got it, using this github's editor, the slash is swalled unlesse you mark the expression as Code (<>) or use a double slash (`\\`)

Anyway, thanks a lot!

All the best ;-)

**Comment by mattslay** [comment]
Fixed.  Thanks for reporting.
