### ISSUE TITLE
Does not treat [ ] as strings

### ISSUE THREAD

**Issue by sjellenoff** [mattslay/Visual-FoxPro-language-template-for-Visual-Studio-Code#8]
Love this project, but unfortunately I've inherited some very large prg files, and the developer used [ and ] to identify strings in many places, and the syntax coloring is not treating it as a string. To make it worse, if there are other string deliminters embedded, like:

``mystring = [<a href="hi">]``

it often throws off the rest of the PRG file coloring all together, forcing me to not use that file in Visual Code.

I'm guessing this may not be an easy fix, but hoping some day you can approach it.

Thanks again for the tool, it's really great otherwise.

**Comment by mattslay** [comment]
Thanks. I'm not likely to dive into this matter, as my focus in other things right now. However, please dive in yourself and see what you can learn about the module. I'm sure it could be fixed... And i bet *you* can figure it out. There are help forums where people discuss these templates for other languages. That could be of some help.

**Comment by Daju78** [comment]
`		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.foxpro</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.foxpro</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.foxpro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\[\[)</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.foxpro</string>
				</dict>
			</array>
		</dict>`

**Comment by Daju78** [comment]
add above code to foxpro.plist

**Comment by mattslay** [comment]
Thanks Daju78!  I'll check this out to confirm, and I'll update this repo once confirmed.

**Comment by Daju78** [comment]
I also made some change to constant.language.foxpro.
`<dict>
			<key>match</key>
			<string>(?i:\s*\b(Empty|False|Nothing|Null|True)\b|(\.t\.|\.f\.|\.null\.))</string>
			<key>name</key>
			<string>constant.language.foxpro</string>
		</dict>`

**Comment by mattslay** [comment]
Did you make Fork this project on github, and Push these changes to your Fork? If so, please send me a Pull Request, and I can merge it into this code base.

**Comment by Daju78** [comment]
I didn't make fork of this project. I just downloaded from vs.code extension store and make change for my local computer.

**Comment by mattslay** [comment]
Daju78 - will you please me your foxpro.plist file? I tried to paste your code bits into my file, but I could not figure out where to put them in the XML nesting.

mattslay @ jordanmachine (dot) com

**Comment by sjellenoff** [comment]
Thanks Daju78 this is definitely helpful and makes the tool better!
I added his code block after line 467 where the original has the `</dict>` tag.
For the constant.language.foxpro change, I replaced the original's `<string></string>` contents found at line 290 in the original with his version.

Oops, didn't meant to close this, and now can't seem to undo that action. Although you could say it's closed, but I was waiting for Matt to respond first.

**Comment by sjellenoff** [comment]
Ah, found the re-open button.

**Comment by newdatasystems** [comment]
Just plopped in a pull request that fixes this and the * comment bug.

**Comment by Daju78** [comment]
Nice.

**Comment by mattslay** [comment]
@Daju78  _ have now merged in your constants change for .T. and .F. as well as your removal of "Select" and "For" into the changes made by @newdatasystems.

So, I think at this time, I have collection both of your into this repo.

@newdatasystems - you should check out this latest commit and see if you want to pull these changes into your "vscode-foxpro" version that  you placed in the on the marketplace.

BTW @newdatasystems - paste us a link to your extension in the "Merketplace".  I could not find it.

**Comment by mattslay** [comment]
Fixed on 2019-04-12 in pull request merged from @newdatasystems.

**Comment by newdatasystems** [comment]
you can also find it in VS Code by going to the extensions sidebar and typing in "foxpro"
https://marketplace.visualstudio.com/items?itemName=NewDataSystems.foxpro
